module.exports = {
// export default {
  name: 'unicom Admin',
  prefix: 'unicomAdmin',
  footerText: 'livecom 版权所有 © 2017',
 // logo: 'http://localhost:8080/images/logo.png',
 // baseURL: 'http://localhost:8080/admin',
  logo: '/images/logo.png',
  baseURL: '/admin',
  iconFontUrl: '//at.alicdn.com/t/font_c4y7asse3q1cq5mi.js',
  openPages: ['/login'],
  apiPrefix: '/api/v1',
  api: {
    userLogin: '/user/login',
    userLogout: '/user/logout',
    userInfo: '/userInfo',
    users: '/users',
    company: '/company',
    sip: '/sip',
    sip_p: '/sip_p',
    signaltrace: '/signaltrace',
    signaltrace_detail: '/signaltrace/detail',
    signaltrace_delete: '/signaltrace/delete',
    ax: '/ax',
    phone: '/phone',
    traffic: '/traffic',  
    topology: '/topology',    
    bind: '/bind',
    logs: '/logs',    
  },
}
