export default [
	  {
	    id: 1,
	    name: '话务统计',
	    router: '/traffic',
	    icon: 'code-o',
	  }, 

	  {
	    id: 2,
	    name: '数据配置',
	    icon: 'setting',
	  },
	  { 
	    id: 21,
	    bpid: 2,
	    mpid: 2,
	    name: '企业配置',
	    router: '/company',
	    icon: 'appstore-o',
	  },  
	  {
	    id: 25,
	    bpid: 2,
	    mpid: 2,	    
	    name: '号码段配置',
	    router: '/phone',
	    icon: 'mobile',
	  },
	  {
	    id: 22,
	    bpid: 2,
	    mpid: 2,	    
	    name: 'AX配置',
	    router: '/ax',
	    icon: 'link',
	  },
	  {
	    id: 23,
	    bpid: 2,
	    mpid: 2,	    
	    name: '绑定AXB',
	    router: '/bind',
	    icon: 'paper-clip',
	  },
	  {
	    id: 24,
	    bpid: 2,
	    mpid: 2,	    
	    name: 'SIP-NIC节点配置',
	    router: '/sip',
	    icon: 'database',
	  }, 
//	  {
//	    id: 26,
//	    bpid: 2,
//	    mpid: 2,	    
//	    name: 'SIP信令处理节点配置',
//	    router: '/sip_p',
//	    icon: 'scan',
//	  }, 

      {
	    id: 3,
	    name: '数据监控',
	    icon: 'dot-chart',
	  },	
     { 
	    id: 33,
	    bpid: 3,
	    mpid: 3,
	    name: '系统网络拓扑',
	    router: '/topology',
	    icon: 'fork',
	  }, 
	   { 
	    id: 31,
	    bpid: 3,
	    mpid: 3,
	    name: '信令跟踪',
	    router: '/signaltrace',
	    icon: 'code-o',
	  },
	  { 
	    id: 32,
	    bpid: 3,
	    mpid: 3,
	    name: '操作日志',
	    router: '/logs',
	    icon: 'clock-circle-o',
	  },		

	  {
	    id: 4,
	    name: '管理员账号管理',
	    icon: 'user',
	    router: '/users',
	 }, 	  
]
